--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pupggerss/PlaceholderApi
build-by-default: true
branches:
- main
projects:
  PlaceholderApi:
    path: ""
    model: virion
    type: library
...
